name: Deploy Hello World Web App

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/deploy-webapp.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v4
        with:
          name: web-content
          path: web/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: web-content
          path: web/

      - name: 'Archive static site'
        run: |
          cd web
          zip -r ../webapp.zip .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'simple-hello-webapp' # Must match the name in Terraform
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: webapp.zip 